[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes won't work in static deployment
# You'll need to set up environment variables in Netlify UI:
# - OPENAI_API_KEY
# - DATABASE_URL (if using database features) 